#ifndef TURN_BASED_GAME_GAMECONFIG_H
#define TURN_BASED_GAME_GAMECONFIG_H

#define MAX_PLAYERS 2
#define MAX_HEROES_PER_PLAYER 4

#define FIELD_W 2
#define FIELD_H 4


#endif //TURN_BASED_GAME_GAMECONFIG_H
